[project]
name = "agent_c-tools"
version = "0.1.3"
description = "Reference tools / tool interfaces for Agent C"
dependencies = [
    "agent_c-core>=0.1.3",
    "ts_tool>=0.1.1",  # ace_proto package
    "pandas==2.2.3", # googletrends, dynamics, database_query/dynamics/salesforce
    "mermaid-py==0.8.0", # mermaid
    "feedparser==6.0.11", # rss
    "readability-lxml==0.8.1", # web
    "markdownify==0.13.1", # web
    "selenium==4.25.0", # web, dynamics
    "httpx>=0.27", # weather, web
    "duckduckgo_search==7.5.5", # web_search-duckduckgo
    "google-search-results==2.4.2", # web_search-google_serp
    "pytrends==4.9.2", # web_search-google_trends
    "requests==2.32.3", # web_search-hacker_news, Youtube_Comments/Search
    "newsapi-python==0.2.7", # web_search-news_api
    "beautifulsoup4==4.12.3", # web_search-seeking_alpha
    "aiohttp==3.10.10", # web_search-seeking_alpha
    "tavily-python==0.5.0", # web_search-tavily
    "wikipedia==1.4.0", # web_search-wikipedia
    "lxml_html_clean",
    "aiobotocore>=2.21.1",
    "azure-storage-blob>=12.25.1",
    "azure-core>=1.32.0",
    "unidiff>=0.7.5",
    "markdown", # markdown html report tool
    "beautifulsoup4==4.12.3", # dynamics (overlap agent_c_tools)
    "pytz==2024.2", # dynamics
    "lxml==5.3.0", # dynamics (overlaps agent_c_voice)
    "lxml_html_clean==0.2.2", # Dynamics (overlaps agent_c_voice)
    "openpyxl==3.1.5", # dynamics, dataframe
    "pyyaml>=6.0", # Configuration file support
    "python-docx==1.1.2", # markdown html report tool
    "sqlparse", # database_query, mariadb
    "mysql-connector-python",
    "playwright>=1.40.0,<1.47.0",  # Pin to versions compatible with pyee 11.x for pyppeteer compatibility
    "pytest-playwright",
    "sympy",
    "numpy>=1.16.0,<2.4", # Constrained for ydata-profiling compatibility, updated for openai-agents[voice] compatibility
    "scipy",
    "matplotlib",
    "pdfplumber",
    "matplotlib==3.9.2", # data_vis
    "seaborn==0.13.2", # data_vis
    "docker==7.1.0", # code_interpreter,
    #"ydata_profiling==4.16.1", # dataframe
    "scikit-learn==1.5.2",  # dataframe
    "urllib3>=2.0.0",  # For types-requests compatibility
    "google-api-python-client==2.149.0",     # Core Google API client
    "google-auth-httplib2==0.2.0",        # Auth library for HTTP/2
    "google-auth-oauthlib==1.2.1",        # OAuth 2.0 library
    "google-auth==2.35.0",                # Google authentication library
    "python-dateutil>=2.8.2",            # For handling GMAIL dates and times
    "email-validator==2.2.0",           # For validating email addresses
    "simple_salesforce==1.12.6", # salesforce
    "linkedin-api==2.0.3", # linked_in
    "requests==2.32.3", # youtube
    "youtube_transcript_api==1.0.3", # YouTube_Transcript
    "huggingface_hub==0.33.0",
    "pyppeteer"

]

requires-python = ">=3.12"
authors = [
    { name = "Donavan Stanley", email = "donavan.stanley@centricconsulting.com" },
    { name = "Joe Ours", email = "joesph.ours@centricconsulting.com" },
    { name = "Sushant Bhatnagar", email = "sushant.bhatnagar@centricconsulting.com" }
]
maintainers = [
    { name = "Donavan Stanley", email = "donavan.stanley@centricconsulting.com" },
]

readme = "README.MD"
license = { text = "Business Source License 1.1" }
keywords = ["gpt", "claude", "agents", "ai", "centric"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/centricconsulting/agent_c_framework"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
